import "../../styling/Home/Intro.css"
export function Intro(){
    return(
        <>
        <section id="features">
        <div>
        <h1 id="box1" >What can this platform actually do  ?</h1>
        <p id="box2">Our AI Interview Simulator helps you practice real interview questions,improve communication 
skills, receive instant feedback, and build confidence for technical and HR interviews.</p>
        </div>
        <div className="features">

  <div className="card">
    <h3 className="card-title" >🤖   AI-Powered Interviews</h3>
    <p className="card-text" >Practice with intelligent interview questions generated by AI.</p>
  </div>

  <div className="card">
    <h3 className="card-title" >📄   Resume-Based Questions</h3>
    <p className="card-text" >Get questions tailored to your resume and skills.</p>
  </div>

  <div className="card">
    <h3 className="card-title" >🎤   Voice Interviews</h3>
    <p className="card-text" >Answer questions using your microphone like a real interview.</p>
  </div>

  <div className="card">
    <h3 className="card-title" >📊   Performance Analysis</h3>
    <p className="card-text" >Track your strengths and identify areas for improvement.</p>
  </div>

  <div className="card">
    <h3 className="card-title" >⏱️ Interview Timer</h3>
    <p className="card-text" >Practice under realistic time constraints.</p>
  </div>

  <div className="card">
    <h3 className="card-title" >💡  Instant Feedback</h3>
    <p className="card-text" >Receive detailed suggestions after each interview session.</p>
  </div>

</div>
</section>
        </>
    )
}